author:
  name: Barry
  email: studiosmith@yahoo.com
title: 'Listening, learning and proclaiming Truth'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3263488986995071
  brandStrength: 0.8115034124348313
  rhythmicContrast: 0.001227819360792637
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  lightness: 0.3491008342243731
typography_spectrum: 0.4789233859628439
layout_spectrum: 0.9672395
name: INSPIRE AND DELIGHT
