author:
  name: Barry
  email: studiosmith@yahoo.com
title: 'Listening, learning and proclaiming Truth'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7008593
  brandStrength: 0.3657357
  lightness: 0
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  rhythmicContrast: 1
typography_spectrum: 0.6101561961695552
layout_spectrum: 0.1792851085774601
name: INSPIRE AND DELIGHT
